/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
void HardFault_Handler(void);
void MemManage_Handler(void);
void BusFault_Handler(void);
int main(void)
{
    //step1 : enable all configurable exception like usage fault, mem manage fault and bus fault
	uint32_t *pSHCR = (uint32_t*)0xE000ED24 ;
	*pSHCR |= (1<<16); //mem manage
	*pSHCR |= (1<<17); //bus fault
	*pSHCR |= (1<<18); //usage fault

	//step 2 : implement fault handler
	//step 2 will be done outside main

	//step 3: force the processor to execute some undefined instruction
	uint32_t *pSRAM = (uint32_t*)0x20010000;
	*pSRAM = 0xffffffff;

	void(*some_address)(void);
	some_address = (void*)0x20010001;
	some_address();

	//analyze the fault
	for(;;);
}

void HardFault_Handler(void){
	printf("exception : hardfault\n ");
	while(1);
}
void MemManage_Handler(void){
	printf("exception : MemManage\n ");
	while(1);
}
void BusFault_Handler(void){
	printf("exception : busfault\n ");
	while(1);
}
void UsageFault_Handler(void){
	printf("exception : usage\n ");
	while(1);
}
